volumes:
  data_db:
    name: "db-data"
    path: "/data/db"
  logs:
    name: "edgex-logs"
    path: "/edgex/logs"
  consul_config:
    name: "consul-config"
    path: "/consul/config"
  consul_data:
    name: "consul-data"
    path: "/consul/data"


edgex_device_mqtt:
  name: "edgex-device-mqtt"
  port: 49982

